/*
> sql plus
사용자명 입력 : system
비밀번호 입력 : 1234

CREATE USER MULTI IDENTIFIED BY Test09061234 
DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

-- 권한부여
GRANT CONNECT, RESOURCE TO MULTI;
-- GRANT DWROLE TO MULTI;

COMMIT;

> sql plus
사용자명 입력 : MULTI
비밀번호 입력 : MULTI

*/

/*
-- 실행 : CTRL + ENTER
drop user MULTI;

CREATE USER MULTI IDENTIFIED BY Test09061234 
DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

-- 권한부여
GRANT CONNECT, RESOURCE TO MULTI;
-- GRANT DWROLE TO MULTI;

COMMIT;
-- -----------------------------

SELECT * FROM TABS;

CREATE TABLE TEST_1( NAME VARCHAR2(30));

DROP TABLE TEST_1;

SELECT * FROM TEST_1;

INSERT INTO TEST_1 VALUES('LEE');
*/


-- 실행 : 커서를 실행하고자 하는 명령어에 두고 CTRL+ENTER
--		 실행하고자 하는 명령어를 블럭치고 ALT+X ( 여러줄 실행도 가능 )
SELECT * FROM TABS;

-- 한줄 주석
/*여러줄
 * 주
 * 석
 **/

 */

 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
DROP TABLE MYTEST;

CREATE TABLE MYTEST(
	MNO NUMBER,
	MNAME VARCHAR2(20),
	NICKNAME VARCHAR2(20)
);

SELECT * FROM MYTEST;

 



DROP TABLE SCORE;
CREATE TABLE SCORE(
	NAME VARCHAR2(20) PRIMARY KEY,
	KOR NUMBER NOT NULL,
	ENG NUMBER NOT NULL,
	MATH NUMBER NOT NULL,
	SUM NUMBER,
	AVG NUMBER,
	GRADE CHAR(2) CHECK(GRADE IN ('A', 'B', 'C', 'D', 'F'))
);

INSERT INTO SCORE VALUES('LEE', 100, 100, 100, 300, 100.0, 'A');
SELECT * FROM SCORE;



-------------------------------

DROP TABLE MYBOARD;

CREATE TABLE MYBOARD(
	MYNO NUMBER PRIMARY KEY,
	MYNAME VARCHAR2(100) NOT NULL,
	MYTITLE VARCHAR2(1000) NOT NULL,
	MYCONTENT VARCHAR2(4000) NOT NULL,
	MYDATE DATE NOT NULL
);

CREATE SEQUENCE SEQ_MYBOARD
NOCACHE;

SELECT * FROM MYBOARD;

INSERT INTO MYBOARD
VALUES(SEQ_MYBOARD.NEXTVAL, '관리자', '게시판 테스트', '테스트 중입니다.
1234567ABCD', CURRENT_DATE);

DROP TABLE MVCBOARD;
DROP SEQUENCE SEQ_MVCBOARD;
CREATE TABLE MVCBOARD(
	SEQ NUMBER PRIMARY KEY,
	WRITER VARCHAR2(100) NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(2000) NOT NULL,
	REGDATE DATE NOT NULL
);

CREATE SEQUENCE SEQ_MVCBOARD
NOCACHE;

INSERT INTO MVCBOARD
VALUES(SEQ_MVCBOARD.NEXTVAL, '관리자', '테스트 중', '테스트 1234 ABCD', '20/02/22');

SELECT * FROM MVCBOARD;


------------------------------------------

CREATE TABLE MYMEMBER(
	MYNO NUMBER PRIMARY KEY,
	MYID VARCHAR2(500) NOT NULL UNIQUE,
	MYPW VARCHAR2(500) NOT NULL,
	MYNAME VARCHAR2(300) NOT NULL,
	MYADDR VARCHAR2(4000) NOT NULL,
	MYPHONE VARCHAR2(20) NOT NULL UNIQUE,
	MYEMAIL VARCHAR2(100) NOT NULL UNIQUE,
	MYENABLED VARCHAR2(2) NOT NULL CHECK(MYENABLED IN('Y','N')),
	MYROLE VARCHAR2(50) NOT NULL
);
CREATE SEQUENCE SEQ_MYMEMBER
NOCACHE;

INSERT INTO MYMEMBER
VALUES(SEQ_MYMEMBER.NEXTVAL,'ADMIN','1234','관리자','관리시 관리구 관리동',
'010-1234-5678','ADMIN@MYMEMBER.COM','Y','ADMIN');

SELECT * FROM MYMEMBER;


UPDATE MYMEMBER SET MYROLE='ADMIN' WHERE MYNO=1;

-------------------------
DROP TABLE MYMVCBOARD;

CREATE TABLE MYMVCBOARD(
	SEQ NUMBER PRIMARY KEY,
	WRITER VARCHAR2(200) NOT NULL,
	TITLE VARCHAR2(2000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	REGDATE DATE NOT NULL
);

CREATE SEQUENCE SEQ_MYMVCBOARD
NOCACHE;

INSERT INTO MYMVCBOARD
VALUES(SEQ_MYMVCBOARD.NEXTVAL, '관리자', '테스트 중..', '테스트 중입니다~
1234 ABCD ', '22/02/22');

SELECT * FROM MYMVCBOARD;









